### ISSUE TITLE
Package request for ekstertera

### ISSUE THREAD

**Issue by skobkin** [yandex-gentoo/overlay#18]
It'd be nice to have [ekstertera](https://github.com/abbat/ekstertera) package in this overlay.

For example as `net-misc/ekstertera`.

**Comment by msva** [comment]
Well, it seems, this issue become obsolete: Qt5 is, actually, EOL already (and the extended support until May'2025 is, actually, for "subscribers", not for everyone).
And this project looks abandoned and have no commits since 3 years already (and it definitelly not ported on Qt6)

So, I guess, it would not worth to create an ebuild for thing which main dependencies can be dropped from gentoo in not-so-long-distance future :shrug:

**Comment by vitaly-zdanevich** [comment]
> And this project looks abandoned and have no commits since 3 years already

Maybe it just works :)

**Comment by vitaly-zdanevich** [comment]
If it has deb - it is not difficult to create an ebuild for it.

**Comment by vitaly-zdanevich** [comment]
And I think, if qt5 is very popular - it will be difficult to drop it, like Python 2.

**Comment by msva** [comment]
> If it has deb - it is not difficult to create an ebuild for it.

Well, it is not hard even to make ebuild for buulding itt from source (I just lackinng of time all that time to do this).

But it will be sad if gentoo will decide to drop qt5 in, say, next year.


Although, if I finally find some spare time, I, maybe even port the project to support Qt6 too. There are chances, that it can be relatively easy (unlike qt3->qt4 and qt4->qt5).
